name: Pull and Upload Docker Image

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull your-docker-image:latest  # Replace with your Docker image

      - name: Save Docker image to tar
        run: |
          docker save your-docker-image:latest -o image.tar  # Replace with your Docker image

      - name: Upload tar file to GitHub Actions summary
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar

      - name: Display summary
        run: |
          echo "Docker image has been saved and uploaded."
          echo "![Docker Image](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/docker-image/image.tar)"
