name: Pull and Upload Docker Image

on:
  push:
    branches:
      - main  # Change this to your target branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: |
          docker pull fooololo/aipan-netdisk-search:latest  # Replace with your Docker image

      - name: Save Docker image to tar
        run: |
          docker save fooololo/aipan-netdisk-search:latest -o image.tar  # Replace with your Docker image

      - name: Upload tar file to GitHub Actions summary
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

      - name: Display summary
        run: |
          echo "Docker image has been saved and uploaded."
          echo "You can download it from the artifacts section."
